{"name": "test_case_create_discard", "status": "broken", "statusDetails": {"message": "TypeError: 'dict' object is not callable", "trace": "self = <test_lawsuit.TestLawsuit object at 0x0E1C9EB0>\n\n    def test_case_create_discard(self):\n        driver = self.driver\n        lawsuit = LawsuitPage(driver)\n        self.login()\n        self.case_create()\n>       lawsuit.discard_case()\n\ntest_lawsuit.py:42: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Pages.LawsuitPage.LawsuitPage object at 0x0E1D5790>\n\n    def discard_case(self):\n        # self.driver.find_element_by_css_selector(self.discard_btn_css).click()\n>       case_count = self.driver.find_element_by_xpath(self.case_table_xpath).size()\nE       TypeError: 'dict' object is not callable\n\n..\\Pages\\LawsuitPage.py:245: TypeError"}, "attachments": [{"name": "stdout", "source": "c0d9196f-3a64-42be-9b11-a91812f8785a-attachment.txt", "type": "text/plain"}], "start": 1567776771472, "stop": 1567776783328, "uuid": "fe86a77b-a8fc-4d35-9590-e36bc7a366ef", "historyId": "6b73d4e87a8a97cd0631bd53a9a23c93", "testCaseId": "5459b1f8834de19a4ccf80ba6a82610f", "fullName": "test_lawsuit.TestLawsuit#test_case_create_discard", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_lawsuit"}, {"name": "subSuite", "value": "TestLawsuit"}, {"name": "host", "value": "EVT01066NB"}, {"name": "thread", "value": "5768-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_lawsuit"}]}