{"name": "test_login_fail", "status": "passed", "attachments": [{"name": "stdout", "source": "9c419e7f-0fc5-4af0-9a5b-aeedfcbe3d63-attachment.txt", "type": "text/plain"}], "start": 1567592173913, "stop": 1567592174631, "uuid": "6f017baf-2a21-47d0-a449-1e70ae15cef4", "historyId": "9732bff26ecc3db3e288176b50591e3b", "testCaseId": "bc42afa9e5dcbd6d9ce70a0cfd211af7", "fullName": "test_login.TestLogin#test_login_fail", "labels": [{"name": "feature", "value": "Login Fail"}, {"name": "severity", "value": "normal"}, {"name": "story", "value": "The user should not be entered with wrong credentials"}, {"name": "parentSuite"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "EVT01066NB"}, {"name": "thread", "value": "16224-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}