{"name": "test_login_fail", "status": "passed", "attachments": [{"name": "screenshot", "source": "1b066727-3d51-4aec-8263-2b2a70015640-attachment.png", "type": "image/png"}], "start": 1569059378181, "stop": 1569059379629, "uuid": "dcc2e468-e3a2-4bc6-b924-e937a572d993", "historyId": "9732bff26ecc3db3e288176b50591e3b", "testCaseId": "e9e9b8493baf09428412d8c9fc1e78f9", "fullName": "test_1_login.TestLogin#test_login_fail", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "Login Success and Fail"}, {"name": "story", "value": "Failed login"}, {"name": "parentSuite"}, {"name": "suite", "value": "test_1_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "EVT01066NB"}, {"name": "thread", "value": "14468-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_1_login"}], "links": [{"type": "test_case", "url": "TESTCASE-2", "name": "TESTCASE-2"}]}