{"name": "test_add_evidence_pdf", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'LocatorsCaseDetails' has no attribute 'evidencepdf_div_class_xpath'", "trace": "self = <test_case_details.TestCaseDetails object at 0x0DB9E670>\n\n    def test_add_evidence_pdf(self):\n        driver = self.driver\n        self.login()\n>       case_details = CaseDetails(driver)\n\ntest_case_details.py:55: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Pages.CaseDetailsPage.CaseDetails object at 0x0DB9EA50>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"284a579e8b577d59f1f09066ab7d044e\")>\n\n    def __init__(self, driver):\n        self.driver = driver\n        self.table_last_row_xpath = LocatorsCaseDetails.table_last_row_xpath\n        self.expense_tab_id = Locators.expense_tab_id\n        self.tab_h4_title_class = LocatorsCaseDetails.tab_h4_title_class\n    \n        self.received_payment_txtbox_id = LocatorsCaseDetails.received_payment_txtbox_id\n        self.received_payment_currency_dropbox_id = LocatorsCaseDetails.received_payment_currency_dropbox_id\n        self.received_payment_detail_txtbox_id = LocatorsCaseDetails.received_payment_detail_txtbox_id\n        self.received_payment_date_datetime_id = LocatorsCaseDetails.received_payment_date_datetime_id\n        self.received_payment_add_btn_xpath = LocatorsCaseDetails.received_payment_add_btn_xpath\n    \n        self.expense_and_payment_div_id = LocatorsCaseDetails.expense_and_payment_div_id\n    \n        self.expense_txtbox_id = LocatorsCaseDetails.expense_txtbox_id\n        self.expense_dropbox_id = LocatorsCaseDetails.expense_dropbox_id\n        self.expense_detail_txtbox_id = LocatorsCaseDetails.expense_detail_txtbox_id\n        self.expense_date_datetime_id = LocatorsCaseDetails.expense_date_datetime_id\n        self.expense_add_btn_xpath = LocatorsCaseDetails.expense_add_btn_xpath\n    \n        self.add_new_evidence_btn_id = LocatorsCaseDetails.add_new_evidence_btn_id\n        self.evidence_tab_id = Locators.evidence_tab_id\n        self.add_new_evidence_file_btn_id = LocatorsCaseDetails.add_new_evidence_file_btn_id\n        self.delete_evidence_attachment_btn_xpath = LocatorsCaseDetails.delete_evidence_attachment_btn_xpath\n>       self.evidence_pdf_div_class_xpath = LocatorsCaseDetails.evidencepdf_div_class_xpath\nE       AttributeError: type object 'LocatorsCaseDetails' has no attribute 'evidencepdf_div_class_xpath'\n\n..\\Pages\\CaseDetailsPage.py:48: AttributeError"}, "start": 1568412562737, "stop": 1568412569621, "uuid": "3b2a62c6-3480-4d4b-9f13-267cff02a50b", "historyId": "4f7a5ddc0b7cb28441ff50298fc8f8b0", "testCaseId": "0adf1ee14a27e3fd86dd27f25091aade", "fullName": "test_case_details.TestCaseDetails#test_add_evidence_pdf", "labels": [{"name": "parentSuite"}, {"name": "suite", "value": "test_case_details"}, {"name": "subSuite", "value": "TestCaseDetails"}, {"name": "host", "value": "EVT01066NB"}, {"name": "thread", "value": "5544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case_details"}]}