{"name": "test_login_fail", "status": "passed", "attachments": [{"name": "screenshot", "source": "a7155921-74eb-4d8c-86e6-60e480b18c21-attachment.png", "type": "image/png"}], "start": 1569059761687, "stop": 1569059762989, "uuid": "22b1ffe2-a469-42f4-9566-2c8af6674a72", "historyId": "9732bff26ecc3db3e288176b50591e3b", "testCaseId": "e9e9b8493baf09428412d8c9fc1e78f9", "fullName": "test_1_login.TestLogin#test_login_fail", "labels": [{"name": "severity", "value": "critical"}, {"name": "story", "value": "Failed login"}, {"name": "feature", "value": "Login Success and Fail"}, {"name": "parentSuite"}, {"name": "suite", "value": "test_1_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "EVT01066NB"}, {"name": "thread", "value": "11536-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_1_login"}], "links": [{"type": "test_case", "url": "https://www.google.com", "name": "Testcase:2"}]}